### ISSUE TITLE
Trading TWS session is connected from a different IP address

### ISSUE THREAD

**Issue by jordics** [ashpipe/EasyIB#1]
Hi!

I wanted to try this library but when I try the sample code I just receive this error:

`{'error': 'Trading TWS session is connected from a different IP address'}`

Any idea about if this is a bug or theres something wrong?

**Comment by jordics** [comment]
No, this is weird in fact (I assumed was a but from IB). I'm using the Client Portal Gateway... but I get this error. I don't have even installed the TWS

**Comment by ashpipe** [comment]
Hmm, that's interesting.
What do you get when you type the following command in the shell terminal?
`curl -X GET "https://localhost:5000/v1/api/one/user" -k`

**Comment by jordics** [comment]
I found the reason: I was authenticated using the paper account. No idea why it says "TWS session" because I have never used it, it must be a minor issue in their API. Thanks! Good work!

**Comment by ashpipe** [comment]
Cool, thanks. Just want to note that paper account should work fine as well, but maybe you need to initialize it first from your main account.

**Comment by ashpipe** [comment]
Just for anyone having this error, I experienced this error when my account was logged in my web browser at the same time.

**Comment by inagib21** [comment]
Hey im getting this same error, but im not logged in the browser at the same time.
