### ISSUE TITLE
Is it possible to get streaming market data with ibeam?

### ISSUE THREAD

**Issue by desmondsy** [ashpipe/EasyIB#6]
how would one use ibeam to get a continuous stream of market data (or is it not currently possible)? It is easy to do with the native api but it requires the gateway UI to be open, which is quite inconvenient.

**Comment by ashpipe** [comment]
I believe this question should be posted at the Ibeam GitHub repository (https://github.com/Voyz/ibeam/issues). 
Anyways, it seems WebSocket streaming is possible according to https://interactivebrokers.github.io/cpwebapi/RealtimeSubscription.html
